version: '3'
services:
  db:
    #image: mysql:latest
    build:
      context: ./db
      dockerfile: Dockerfile.dev
    environment:
      MYSQL_ROOT_PASSWORD: pw 
  php:
    #image: php:latest
    build:
      context: ./php
      dockerfile: Dockerfile.dev
    volumes:
      - ./app:/var/www/app
      - ./php/log:/var/log
    depends_on:
      - db
  httpd:
    #image: httpd:latest
    build:
      context: ./httpd
      dockerfile: Dockerfile.dev
    volumes:
      - ./app:/var/www/app
    ports:
      - 8080:80
    depends_on:
      - php
  node:
    build:
      context: ./node
      dockerfile: Dockerfile.dev
    volumes:
      - ./app:/app
    tty: true
